apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
      component: backend
  template:
    metadata:
      labels:
        app: django
        component: backend
    spec:
      containers:
        - name: app
          image: ghcr.io/tayson-7/django-app:runserver
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secrets