apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: django-servicemonitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: django
      component: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
