apiVersion: v1
kind: Service
metadata:
  name: service-django
spec:
  type: ClusterIP
  selector:
    app: django
    component: backend
  ports:
    - port: 8000
      targetPort: 8000
      name: http

