apiVersion: v1
kind: Service
metadata:
  name: service-frontend
spec:
  type: LoadBalancer
  selector:
    app: django
    component: frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
