apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: {{.Values.namespace}}
stringData:
  POSTGRES_USER: {{.Values.postgres.POSTGRES_USER}}
  POSTGRES_PASSWORD: {{.Values.postgres.POSTGRES_PASSWORD}}
