apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: {{ .Values.namespace }}
data:
  DEBUG: {{ .Values.django.DEBUG | quote }}
  ALLOWED_HOSTS: {{ .Values.django.ALLOWED_HOSTS | quote }}
  POSTGRES_DB: {{ .Values.database.POSTGRES_DB | quote }}
  DB_HOST: {{ .Values.database.DB_HOST | quote }}
