apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SECRET_KEY: django-insecure-unj@!ly)+9#%%v92@4jh*r)u4oag7w9b-w5dq7*^p9x!uplkf(
  POSTGRES_USER: {{ .Values.database.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.database.POSTGRES_PASSWORD }}