apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.django.SECRET_KEY | quote }}
  POSTGRES_USER: {{ .Values.database.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.POSTGRES_PASSWORD | quote }}
