apiVersion: v1
kind: Service
metadata:
  name: service-django
  namespace: django-app
spec:
  type: LoadBalancer
  selector:
    app: django
    component: backend
  ports:
    - port: 8000
      targetPort: 8000

