apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
      component: frontend
  template:
    metadata:
      labels:
        app: django
        component: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/tayson-7/django-app:frontend-react
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
