apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dep
  namespace: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
      component: db
  template:
    metadata:
      labels:
        app: django
        component: db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: POSTGRES_DB
          envFrom:
            - secretRef:
                name: django-secrets